### ISSUE TITLE
Let's have official images using UBI

### ISSUE THREAD

**Issue by Conan-Kudo** [Ilyes512/caddy-docker#5]
There's a great, high-quality set of base images with good commercial support that we should leverage for the official Caddy container images: The [Red Hat Universal Base Image](https://developers.redhat.com/products/rhel/ubi/). Using `ubi8` as the base gives us an excellent, well-supported stack that will work well for community and commercial users alike.

@fatherlinux has been working on this for a while now, and I think he'd be pleased as punch if we used it for caddy. And if there's anything missing we need, we can ask him about fixing it. It would also let us leverage the official Caddy RPMs that @carlwgeorge has made...

**Comment by Ilyes512** [comment]
As @carlwgeorge mentioned (on slack) there is currently no (trusted/official) golang 1.13 support using UBI8. He suggested we should use [UBI7](https://access.redhat.com/containers/#/registry.access.redhat.com/ubi7/ubi) so we could use the copr [caddy](https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/) repository.

**Comment by Conan-Kudo** [comment]
That works for me.

**Comment by carlwgeorge** [comment]
Just did a quick test and this works with ubi7-minimal as well.  The image size comes out to 213MB.

```
CONTAINER=$(buildah from --pull-always registry.access.redhat.com/ubi7/ubi-minimal)
buildah run $CONTAINER -- bash -c 'curl https://copr.fedorainfracloud.org/coprs/g/caddy/caddy/repo/epel-7/group_caddy-caddy-epel-7.repo > /etc/yum.repos.d/caddy.repo'
buildah run $CONTAINER -- rpm --import https://copr-be.cloud.fedoraproject.org/results/@caddy/caddy/pubkey.gpg
buildah run $CONTAINER -- microdnf install caddy
buildah run $CONTAINER -- microdnf clean all
buildah config --entrypoint '["/usr/bin/caddy"]' $CONTAINER
buildah commit $CONTAINER caddy
buildah rm $CONTAINER
```

```
$ podman run -it --rm caddy help
Caddy is an extensible server platform.

usage:
  caddy <command> [<args...>]

commands:
  adapt           Adapts a configuration to Caddy's native JSON
  environ         Prints the environment
  file-server     Spins up a production-ready file server
  hash-password   Hashes a password and writes base64
  help            Shows help for a Caddy subcommand
  list-modules    Lists the installed Caddy modules
  reload          Changes the config of the running Caddy instance
  reverse-proxy   A quick and production-ready reverse proxy
  run             Starts the Caddy process and blocks indefinitely
  start           Starts the Caddy process in the background and then returns
  stop            Gracefully stops the running Caddy process
  validate        Tests whether a configuration file is valid
  version         Prints the version

Use 'caddy help <command>' for more information about a command.

Full documentation is available at:
https://github.com/caddyserver/caddy/wiki/v2:-Documentation
```

**Comment by Ilyes512** [comment]
Moved to https://github.com/caddyserver/caddy-docker/issues/5
